# Data preparation configuration for CIFAR10DVS dataset
# Frame mode: Event count with 10000 events per frame

base:
  seed: 42

data:
  # Dataset selection
  name: CIFAR10DVS

  # Storage paths (will use SCRATCH_STORAGE_DIR if set)
  data_root: data/

  # Frame slicing mode
  frame_mode: event_count

  # Event count mode parameters
  events_per_frame: 10000
  overlap: 0.75

  # Preprocessing parameters
  denoise_time: 5000       # Denoise filter time in microseconds (0 to disable)

  # Processing settings (multiprocessing)
  num_threads: 8

  # Dataset splitting
  test_split: 0.15
  val_split: 0.05

  # Cache control
  reset_cache: true
