# @package _global_
# CIFAR10-DVS data preparation

data:
  name: CIFAR10DVS
  events_per_frame: 20000
  overlap: 0.75
  denoise_time: 5000
  num_threads: 16
  test_split: 0.15
  val_split: 0.05
  reset_cache: false
