export USERNAME=$(whoami)
export PROJECT_NAME="difflogic-tonic"
export PROJECT_STORAGE_DIR="/itet-stor/${USERNAME}/net_scratch/projects_storage/${PROJECT_NAME}"
export SCRATCH_STORAGE_DIR="/scratch/${USERNAME}/${PROJECT_NAME}"

export REMOTE_SERVER="tik42x.ethz.ch"
export CODE_STORAGE_DIR="/home/${USERNAME}/code/${PROJECT_NAME}"
export DATA_STORAGE_DIR="${PROJECT_STORAGE_DIR}/data"
export MODEL_STORAGE_DIR="${PROJECT_STORAGE_DIR}/models"
export SINGULARITY_SCRATCH_STORAGE_DIR="${SCRATCH_STORAGE_DIR}/singularity"
export SINGULARITY_PROJECT_STORAGE_DIR="${PROJECT_STORAGE_DIR}/singularity"
export SINGULARITY_CONTAINER_SCRATCH="${SINGULARITY_SCRATCH_STORAGE_DIR}/difflogic.sif"
export SINGULARITY_CONTAINER_PROJECT="${SINGULARITY_PROJECT_STORAGE_DIR}/difflogic.sif"
