# @package _global_
# DiffLogic model configuration

model:
  model_type: DiffLogic
  difflogic:
    architecture: "fully_connected"
    num_neurons: 64000
    num_layers: 4
    connections: "random"
    grad_factor: 1.0
    tau: 10.0

base:
  wandb:
    tags: ["difflogic"]
