base:
  seed: 42
  job_id: "baseline_difflogic_run"
  wandb:
    entity: null
    run_name: null
    tags: ["cifar10dvs", "difflogic"]
    notes: null

data:
  name: CIFAR10DVS  # Options: NMNIST, CIFAR10DVS

train:
  epochs: 3
  learning_rate: 1e-2
  log_interval: 250
  debugging_steps: 1000
  save_model: false
  checkpoint_interval_minutes: 10.0
  model_path: models/
  device: cuda
  dtype: float16 # options: float16, bfloat16, float32
  dataloader:
    batch_size: 64
    num_workers: 6
    prefetch_factor: 5
    pin_memory: true
    shuffle_train: true

model:
  model_type: DiffLogic
  difflogic:
    architecture: "fully_connected"  # Options: fully_connected and convolutional (not implemented yet)
    num_neurons: 4000
    num_layers: 4
    connections: "random"
    grad_factor: 1.0
    tau: 10.0