# @package _global_

defaults:
  - dataset: cifar10dvs
  - model: difflut
  - _self_

base:
  seed: 42
  job_id: "baseline_difflut_run"
  wandb:
    online: true
    tags: ["cifar10dvs", "difflut"]

train:
  learning_rate: 1e-3
  debugging_steps: 1000
  dtype: bfloat16
  dataloader:
    num_workers: 6
    prefetch_factor: 5
