base:
  seed: 42
  job_id: "baseline_difflogic_run"
  wandb:
    entity: null
    run_name: null
    tags: ["cifar10dvs", "difflogic"]
    notes: null

data:
  name: CIFAR10DVS  # Options: NMNIST, CIFAR10DVS

  # Specify which cached dataset variant to use (matches prepare_data output)
  # Examples: "events_20000_overlap0_denoise5000", "time_10000_overlap0_denoise5000"
  # Leave as null to use default cache (backward compatibility)
  cache_identifier: null  # or "events_20000_overlap0_denoise5000"

  # Input transforms
  downsample_pool_size: 4  # Max pooling: 128x128 -> 64x64 (2), 128x128 -> 32x32 (4), null for no downsampling

  # Data augmentation (applied only to training set)
  augmentation:
    horizontal_flip: false
    vertical_flip: false
    salt_pepper_noise: 0.20  # Probability [0.0-1.0] to flip random pixels (20% here)

train:
  epochs: 10
  learning_rate: 1e-2
  log_interval: 250
  debugging_steps: 1000
  save_model: false
  checkpoint_interval_minutes: 10.0
  model_path: models/
  device: cuda
  dtype: float16 # options: float16, bfloat16, float32
  dataloader:
    batch_size: 64
    num_workers: 6
    prefetch_factor: 5
    pin_memory: true
    shuffle_train: true

model:
  model_type: DiffLogic
  difflogic:
    architecture: "fully_connected"  # Options: fully_connected and convolutional (not implemented yet)
    num_neurons: 32000
    num_layers: 4
    connections: "random"
    grad_factor: 1.0
    tau: 10.0