# @package _global_

defaults:
  - dataset: nmnist
  - model: difflogic
  - optional experiment: null
  - _self_

base:
  seed: 42
  job_id: "default_job"
  debug: false
  wandb:
    online: false
    project: "difflogic-tonic"
    entity: null
    run_name: null
    tags: []
    notes: null

data:
  name: ???
  cache_identifier: null
  downsample_pool_size: null
  augmentation:
    horizontal_flip_probability: 0.0
    vertical_flip_probability: 0.0
    random_crop_padding: 0
    salt_pepper_noise: 0.0

train:
  epochs: 10
  learning_rate: 1e-2
  log_interval: 250
  debugging_steps: 5
  save_model: false
  checkpoint_interval_minutes: 10.0
  model_path: models/
  device: cuda
  dtype: float16
  dataloader:
    batch_size: 64
    num_workers: 4
    prefetch_factor: 2
    pin_memory: true
    shuffle_train: true
  scheduler:
    enabled: false
    type: "step"
    step_size: 10
    gamma: 0.1
    min_lr: 1e-6
    factor: 0.5
    patience: 5
  early_stopping:
    enabled: false
    monitor: "val/acc"
    patience: 10
    mode: "max"
    min_delta: 0.0
  lightning:
    enable_progress_bar: true
    log_every_n_steps: 50
    gradient_clip_val: null
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 2

model:
  model_type: ???
