# @package _global_

defaults:
  - dataset: nmnist
  - model: difflut
  - _self_

base:
  seed: 42
  job_id: "baseline_difflut_run"
  wandb:
    online: false
    tags: ["nmnist", "difflut"]

train:
  learning_rate: 1e-2
  debugging_steps: 5
  dtype: float16
  dataloader:
    num_workers: 6
    prefetch_factor: 5
