base:
  seed: 42
  job_id: "baseline_cnn_run"
  wandb:
    entity: null
    run_name: null
    tags: ["nmnist", "cnn"]
    notes: null

data:
  name: NMNIST  # Options: NMNIST, CIFAR10DVS

train:
  epochs: 10
  learning_rate: 3e-4
  log_interval: 1
  debugging_steps: 10
  save_model: false
  checkpoint_interval_minutes: 10.0
  model_path: models/
  device: cuda
  dtype: bfloat16 # options: float16, bfloat16, float32
  dataloader:
    batch_size: 64
    num_workers: 6
    prefetch_factor: 5
    pin_memory: true
    shuffle_train: true

model:
  model_type: CNN
  cnn:
    conv1_channels: 32
    conv2_channels: 64
    fc_hidden_size: 128
