base:
  seed: 42
  job_id: "baseline_mlp_run"
  wandb:
    entity: null
    run_name: null
    tags: ["nmnist", "mlp"]
    notes: null

data:
  name: NMNIST  # Options: NMNIST, CIFAR10DVS

train:
  epochs: 3
  learning_rate: 1e-3
  log_interval: 250
  debugging_steps: 5
  save_model: false
  checkpoint_interval_minutes: 10.0
  model_path: models/
  device: cuda
  dtype: bfloat16 # options: float16, bfloat16, float32
  dataloader:
    batch_size: 64
    num_workers: 6
    prefetch_factor: 5
    pin_memory: true
    shuffle_train: true

model:
  model_type: MLP
  mlp:
    hidden_size: 512
    num_hidden_layers: 1
