# @package _global_

defaults:
  - prepare_data: nmnist
  - _self_

base:
  seed: 42

data:
  name: ???
  data_root: data/
  frame_mode: event_count
  events_per_frame: 5000
  time_window: null
  overlap: 0.0
  denoise_time: 1000
  num_threads: 6
  test_split: 0.1
  val_split: 0.1
  reset_cache: false
  output_suffix: null
